apiVersion: v1
kind: Service
metadata:
  name: db-cluster-ip-service
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - name: db-port
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: db
  