apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80 # serive port
      targetPort: 80 # target port of the pods
      nodePort: 32000 #This port is enable on node to send the traffic
      protocol: TCP
  selector:
      app: 000h/result
  